ita-social-projects/GreenCityTests

- .gitignore
- src/test/java/com/softserve/edu/greencity/ui/data/UserRepository.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/HabitComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/HabitsContainer.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/LoginComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/MyCabinetPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/LoginDropdown.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/MainMenuDropdown.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/SmallHeightPart.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/TopPart.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/EconewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/tipstricks/TipsCardsContainer.java
- src/test/java/com/softserve/edu/greencity/ui/pages/tipstricks/TipsTricksPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/GreencityTestRunner.java
- src/test/java/com/softserve/edu/greencity/ui/tests/LoginTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/SmokeTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/TipsTricksTest.java
Add method for signOut in GreencityTestRunner
Refactor HabitComponent, HabitsContainer, SmallHeightPart, SmokeTest, TipsCardsContainer,
Change return value in method successfullyLogin().
Fixed locators in MainMenuDropdown, MyCabinetPage, TipsTricksPage, also add TODO for next refactoring initialize elements.
Fixed checkHabitButtonTop() test.
Add method scrollToElementByCoordinates.
Change credentials to signIn for local.
> Refactor, Fix, Add.

- .gitignore
- src/test/java/com/softserve/edu/greencity/ui/data/UserRepository.java
- src/test/java/com/softserve/edu/greencity/ui/tests/GreenCityTestRunner.java
- src/test/java/com/softserve/edu/greencity/ui/tests/LoginTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/RegisterComponentTest.java
Move all credentials to property file.
Add property file to gitignore.
> Refactor UserRepository.

- src/test/java/com/softserve/edu/greencity/ui/data/econews/NewsDataRepository.java
- src/test/java/com/softserve/edu/greencity/ui/data/econews/Tag.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/MyCabinetPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/TopPart.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/CreateNewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/EconewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/PreViewPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/TagsComponent.java
- src/test/java/com/softserve/edu/greencity/ui/tests/CreateNewsTest.java
- src/test/java/com/softserve/edu/greencity/ui/tools/CheckPage.java
- src/test/java/com/softserve/edu/greencity/ui/tools/DateUtil.java
+make lazy inicialization in CreateNewsPage
+from FillAllCreateNewsFields and FillRequestCreateNewsFields
methods make one universal - FillFields
+make lazy initialization for EconewsPage
+repair publishButton in PreViewPage
+in DateUtil change default date format, add possibility to change it
+create CheckPage class in tools package
it help to check that we already on page that we expect
it has staic method that create Wait for checking one or
many Webelements
-+elete Thread.sleep from MyCabinetPage and add WebdriverWait
> Repair CreateNewsTest from last group

- README.md
- src/test/java/com/softserve/edu/greencity/ui/data/UserRepository.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/GoogleAccountManagerPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/GoogleLoginPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/LoginComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/ManualLoginComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/MyCabinetPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/RegisterComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/TopPart.java
- src/test/java/com/softserve/edu/greencity/ui/pages/tipstricks/TipsTricksPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/GreenCityTestRunner.java
> Add localization to ChromeOption

- README.md
> ReadMe updated.

- src/test/java/com/softserve/edu/greencity/ui/data/econews/NewsData.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNFunctionalityTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNNegativeTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNPositiveTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNSmokeTests.java
- src/test/java/com/softserve/edu/greencity/ui/tools/DBQueries.java
> solution for GC-1303 and GC-1304

- NG_CreateNewsTests_parallel_classes.xml
- src/test/java/com/softserve/edu/greencity/ui/pages/common/MainMenuDropdown.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/EconewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/GreenCityTestRunner.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNFunctionalityTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNNegativeTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNSmokeTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CNTests.java
make more simply and quickly way to CreateNewsPage
> Clean eco news tests

- README.md
- src/test/java/com/softserve/edu/greencity/api/assertions/OwnSecurityAssertions.java
- src/test/java/com/softserve/edu/greencity/api/builders/userbuilder/SignInUserDirector.java
- src/test/java/com/softserve/edu/greencity/api/tests/ownsecurity/signin/SignInNegativeTests.java
- src/test/java/com/softserve/edu/greencity/ui/data/UserRepository.java
Added new construct methods to SignInUserDirector.
> GC1309. Added new assertion. Added new tests.

- src/test/java/com/softserve/edu/greencity/api/assertions/OwnSecurityAssertions.java
- src/test/java/com/softserve/edu/greencity/api/listeners/LogListener.java
- src/test/java/com/softserve/edu/greencity/api/tests/ownsecurity/signin/SignInTests.java
- src/test/java/com/softserve/edu/greencity/ui/pages/cabinet/GoogleLoginPage.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/TopUserComponent.java
- src/test/java/com/softserve/edu/greencity/ui/tests/login/LoginByGoogleTests.java
- src/test/resources/logback.xml
> Add new method to OwnSecurityAssertions.

- RegistrationTest.xml
> test commit some msg

- src/test/java/com/softserve/edu/greencity/ui/pages/econews/EcoNewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/EcoNewsSingleViewTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/runner/GreenCityTestRunner.java
Implemented GC-670 "Verify that User can return to News from single view by clicking ‘Back to news’ button"
> Created SingleNews test. fixed List-view locator.

- src/test/java/com/softserve/edu/greencity/ui/data/econews/NewsDataRepository.java
- src/test/java/com/softserve/edu/greencity/ui/locators/SingleNewsPageLocators.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/SmallWidthPart.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/TopGuestComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/common/TopUserComponent.java
- src/test/java/com/softserve/edu/greencity/ui/pages/econews/SingleNewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/CreateNewsPositiveTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/EcoNewsGridViewTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/EcoNewsListViewTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/EcoNewsSingleViewTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/ForgotPasswordTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/LoginTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/RegisterPageTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/RegistrationTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/runner/GreenCityTestRunner.java
- Adding a bit of documentation,
- starting to implement GC-731,
- moving softAssert to TestRunner
- replacing incorrect assertSoftly() with softAssert
> Soft asserts fix: beginning

- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/GmailManagerPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/LoginComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/ManualLoginComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/MyCabinetPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/common/ForgotPasswordComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/common/MainMenuDropdown.java
- src/main/java/com/softserve/edu/greencity/ui/pages/common/TopPart.java
- src/main/java/com/softserve/edu/greencity/ui/pages/common/TopUserComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/CreateNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/EcoNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemsContainer.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/PreviewPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/SingleNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/tools/ElementsCustomMethods.java
- src/main/java/com/softserve/edu/greencity/ui/tools/UploadFileUtil.java
- src/main/java/com/softserve/edu/greencity/ui/tools/engine/WaitsSwitcher.java
- src/test/java/com/softserve/edu/greencity/ui/tests/runner/GreenCityTestRunner.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegistrationTests.java
Using proper WaitsSwitcher instead of mixing explicit and implicit waits.
Certain stability on CreateNewsPositiveTest, EcoNewsGridViewTest, EcoNewsGridListTest* achieved.
*further investigation on ItemsContainer needed
> Proper waits

- pom.xml
- src/main/java/com/softserve/edu/greencity/ui/api/google/sheets/GoogleSheet.java
- src/main/java/com/softserve/edu/greencity/ui/api/google/sheets/ValueProvider.java
- src/main/java/com/softserve/edu/greencity/ui/data/econews/NewsDataRepository.java
- src/main/java/com/softserve/edu/greencity/ui/locators/EcoNewsPageLocator.java
- src/main/java/com/softserve/edu/greencity/ui/locators/SingleNewsPageLocators.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/CreateNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/EcoNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemsContainer.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/SingleNewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsGridViewTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewsinglenews/EcoNewsSingleViewTest.java
- Newest version of `io.github.bonigarcia` dependency (previous didn't work with Chrome 86)
- Google Sheet was updated, fixing ValuesProvider
- GC-695 and GC-731 implemented
- Fixed infinite scroll on `EcoNewsPage.scrollDown()` (cause: site bug)
- Maximize window before tests in EcoNewsGridViewTest, since some tests change window width
> GC-695 GC-731 and further fixes

- src/main/java/com/softserve/edu/greencity/ui/api/google/sheets/GoogleSheet.java
- src/main/java/com/softserve/edu/greencity/ui/api/google/sheets/ValueProvider.java
- src/main/java/com/softserve/edu/greencity/ui/data/UserRepository.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signin/ForgotPasswordTests.java
Fixed GC-520
Added new data to UserRepository
Changed ValueProvider
> Fixed GC-520

- src/main/java/com/softserve/edu/greencity/ui/locators/EcoNewsPageLocator.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/EcoNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemsContainer.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/SingleNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/TagsComponent.java
- src/main/java/com/softserve/edu/greencity/ui/tools/QuantityItems.java
- src/main/java/com/softserve/edu/greencity/ui/tools/TagsUtill.java
- src/test/java/com/softserve/edu/greencity/ui/assertions/EcoNewsSuggestionsAssertion.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewsinglenews/EcoNewsSingleViewTest.java
Createtd some infrastructure for SingleNews testing.
Improved waitings, but they are still not 100% robust.
> Created test GC-713.

- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsListViewTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewsinglenews/EcoNewsSingleViewTest.java
1. Full path to the default image
2. Assert equals instead of assert true
> Fix GC-725 default image link

- src/main/java/com/softserve/edu/greencity/ui/locators/SingleNewsPageLocators.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/SingleNewsPage.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewsinglenews/EcoNewsSingleViewTest.java
+ added locator of edit button + added method for SingleNewsPage
> implemented test gc-672

- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/ManualRegisterComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/RegisterComponent.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegisterPageTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegistrationTests.java
Fixed GC-519
Fixed GC-509
Fixed GC-213
Fixed GC-212
Fixed GC-205 
Fixed GC-517
Refactored RegisterPageTests and RegistrationTests
> Fixing register page tests

- src/test/java/com/softserve/edu/greencity/api/assertions/ArrayAssertion.java
- src/test/java/com/softserve/edu/greencity/api/assertions/BaseAssertion.java
- src/test/java/com/softserve/edu/greencity/api/tests/signin/SignInTest.java
All tests for Sign in API are implemented
> Sign in API

- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/RegisterComponent.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemComponent.java
- src/test/java/com/softserve/edu/greencity/api/assertions/ArrayAssertion.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CreateNewsPositiveTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/runner/GreenCityTestRunner.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signin/LoginTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsGridViewTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsListViewTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewsinglenews/EcoNewsSingleViewTest.java
Removed some commented code and updated comments
> Commented code

- pom.xml
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/EcoNewsPage.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/dao/EcoNewsDao.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsGridViewTest.java
But time zones problem is still present, so LocalOnly annotation added
> Fixed chronological view

- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/dao/EcoNewsDao.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/services/EcoNewsService.java
- src/test/java/com/softserve/edu/greencity/api/tests/signin/CreateNewsTest.java
- src/test/java/com/softserve/edu/greencity/api/tests/signin/GreenCityAPITestRunner.java
Used service for asserting news creation.
> Created ApiTestRunner with logger inside.

- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegisterPageTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegistrationTests.java
- Deleted some data providers, comments
- Updated some tests
- Changed testNames and Descriptions
> Refactored RegistrationTests

- src/test/java/com/softserve/edu/greencity/api/tests/econews/negative/CreateNewsWithArrayResponseTest.java
- src/test/java/com/softserve/edu/greencity/api/tests/econews/negative/CreateNewsWithDetailedResponseTest.java
- src/test/java/com/softserve/edu/greencity/api/tests/econews/negative/CreateNewsWithShortResponseTest.java
- src/test/java/com/softserve/edu/greencity/api/tests/econews/positive/CreateNewsWithMinimalValuesTest.java
- src/test/java/com/softserve/edu/greencity/api/tests/signin/SignInApiTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/Commentstest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CreateNewsPositiveTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/runner/GreenCityTestRunner.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signin/ForgotPasswordTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signin/LoginTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegisterPageTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/signup/RegistrationTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsGridViewTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewallnews/EcoNewsListViewTests.java
- src/test/java/com/softserve/edu/greencity/ui/tests/viewsinglenews/EcoNewsSingleViewTest.java
added parameters Test(description="GC-000") for allure reports
testName="" is for IDEA and TestNG, and description="" is for Allure
> Test descriptions for Allure

- src/main/java/com/softserve/edu/greencity/api/builders/ownsecurity/SignUpBuilder.java
- src/main/java/com/softserve/edu/greencity/api/clients/OwnSecurityClient.java
- src/main/java/com/softserve/edu/greencity/api/models/ownsecurity/SignUpDto.java
- src/main/java/com/softserve/edu/greencity/api/models/ownsecurity/VerifyEmailDto.java
- src/main/java/com/softserve/edu/greencity/data/users/UserRepository.java
- src/test/java/com/softserve/edu/greencity/api/tests/signup/SignUpApiTest.java
> Sign up api

- src/test/java/com/softserve/edu/greencity/api/assertions/ArrayAssertion.java
- src/test/java/com/softserve/edu/greencity/api/tests/signup/SignUpApiTest.java
> Fixing something

- src/main/java/com/softserve/edu/greencity/ui/pages/econews/CreateNewsPage.java
changed selector for continueEditingButton in CreateNewsPage class
#428
> Fixed GC-607

- src/main/java/com/softserve/edu/greencity/ui/pages/common/TopPart.java
changed selector for getCopyright() method in TopPart class
#426
> Fixed GC-651

- src/main/java/com/softserve/edu/greencity/ui/pages/econews/TagsComponent.java
added method in selectTag(), which initialize elements after clicking on tag
#424
> Fixed selectTag method

- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentTests.java
changed method clickPublishButton() on publishNews() because it works more correctly
#420
> Updated EcoNewsCommentTests class

- src/main/java/com/softserve/edu/greencity/ui/pages/econews/TagsComponent.java
> Fixed GC-623

- src/main/java/com/softserve/edu/greencity/ui/locators/ItemComponentLocators.java
- src/main/java/com/softserve/edu/greencity/ui/pages/econews/ItemComponent.java
changed selector in ItemComponentLocators class
#431
> Fixed GC-333

- src/main/java/com/softserve/edu/greencity/ui/locators/comments/ReplyLocator.java
- src/main/java/com/softserve/edu/greencity/ui/pages/common/ReplyComponent.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/CheckElementOfCommentTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentReplyTests.java
> implemented GC-998 test

- src/test/java/com/softserve/edu/greencity/ui/tests/comments/CheckElementOfCommentTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentReplyTests.java
> implemented GC-995 test

- src/test/java/com/softserve/edu/greencity/ui/tests/comments/CheckElementOfCommentTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentReplyTests.java
> added GC-971 test

- src/test/java/com/softserve/edu/greencity/ui/tests/comments/CheckElementOfCommentTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentReplyTests.java
> implemented GC-963 test

- src/test/java/com/softserve/edu/greencity/ui/tests/comments/EcoNewsCommentReplyTests.java
Fixed tests after created getTemporaryUser method(deleted row with created temporaryUser in each method)
> Implemented GC-780

- src/test/java/com/softserve/edu/greencity/api/tests/comments/CommentsApiTestRunner.java
- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
implemented GC-1154 test, added CommentsApiTestRunner class for comments api tests.
#486
> implemented GC-1154 test

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1155 test

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1163 test

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1169 test

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1171 test

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1172 test

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1174

- src/test/java/com/softserve/edu/greencity/api/tests/comments/EcoNewsCommentsApiTests.java
> implemented GC-1188

- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/dao/EditProfileDao.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/dao/EditProfileSocialNetworksDao.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/entity/EditProfileEntity.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/entity/EditProfileSocialNetworksEntity.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/services/EditProfileService.java
- src/test/java/com/softserve/edu/greencity/ui/tests/editprofile/SocialNetworkLinkTest.java
lAdded classes for working with database, added after method to SocialNetworkLinkTest
> Working with database

- pom.xml
- src/main/java/com/softserve/edu/greencity/ui/elements/CheckBoxElement.java
- src/main/java/com/softserve/edu/greencity/ui/locators/EditProfileLocators.java
- src/main/java/com/softserve/edu/greencity/ui/locators/PreviewPageLocators.java
- src/main/java/com/softserve/edu/greencity/ui/pages/cabinet/editprofile/EditProfilePage.java
- src/main/java/com/softserve/edu/greencity/ui/tools/jdbc/dao/ManagerDao.java
- src/test/java/com/softserve/edu/greencity/ui/tests/runner/DriverSetup.java
> Fix issue #735

- src/test/java/com/softserve/edu/greencity/ui/tests/createnews/CreateNewsPositiveTest.java
> Fix issue #768 GC-656 

- src/main/java/com/softserve/edu/greencity/ui/locators/ubs/OrderDetailsPageLocators.java
- src/main/java/com/softserve/edu/greencity/ui/pages/ubs/OrderDetailsPage.java
- src/main/java/com/softserve/edu/greencity/ui/pages/ubs/ServicesComponents.java
- src/test/java/com/softserve/edu/greencity/ui/tests/ubscourier/EcoStoreTest.java
- src/test/java/com/softserve/edu/greencity/ui/tests/ubscourier/ServiceTest.java
Added tests GC-1952, GC-1953, GC-1951, GC-1950, GC-1949 and unfinished GC-1968
> Added test
